---
title: "Relationship Between Sustainability (SDI) and GDP per Capita"
author: "Karisa Kopecek, Theo S., Treasure Joyce & Brooke Wallasch"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
    html-table-processing: none
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

# 1. Introduction

## Hypothesis

Countries with higher GDP will have higher sustainability scores.

## Objectives

1.  

## Packages

```{r}
library(tidyverse)
library(knitr)
```

## Data

Data from GapMinder

Explanatory Variable: GDP per Capita (<http://gapm.io/dgdpcap_cppp>)

Response Variable: Sustainable Development Index (<http://gapm.io/dsdi>)

```{r}
sustainability <- read_csv("sdi.csv")
#164 countries, 1990 - 2019

gdp <- read_csv("gdp_pcap.csv")
#195 countries, 1800 - 2100
```

# 2. Data Cleaning

```{r}
#pivot longer (each row identified by a country and a year)
sustainability.long <- sustainability |> 
  mutate(across(.cols = '1990':'2019', .fns = ~as.numeric(.x, na.rm = TRUE))) |> 
  pivot_longer(cols = '1990':'2019', 
               names_to = "year", 
               values_to = "sdi")

gdp_long <- gdp |> 
  mutate(across(.cols = '1800':'2100', .fns = ~as.numeric(.x, na.rm = TRUE))) |> 
  pivot_longer(cols = '1800':'2100', 
               names_to = "year", 
               values_to = "gdp")

#left_join and removing rows missing sdi or gdp
df.clean <- sustainability.long |> 
  left_join(gdp_long, join_by(country, year)) |> 
  filter(!if_any(.cols = sdi:gdp, .fns = ~is.na(.x)))

```

# 3. Modeling and Relationship Between Sustainability (SDI) and GDP per capita

```{r}
#preliminary scatterplot
df.clean |> 
  group_by(country) |> 
  summarize(mean.sdi = mean(sdi), mean.gdp = mean(gdp)) |> 
  ggplot(aes(x = mean.gdp, y = mean.sdi))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_classic() +
  labs(x = "GDP per Capita (2017 dollars)", y = "", subtitle = "Sustainable Development Index (SDI)", title = "Relationship between GDP per capita and Sustainability (SDI) \n from 1990 to 2019")
  
```

# 4. Cross-Validation

```{r}

```

# 5. Conclusion

```{r}

```
